language: csharp
install:
- nvm install 8.9.1

script:
  - ./build.sh --azure_uri=$azure_uri --azure_uname=$azure_uname --azure_pass=$azure_pass

notifications:
  email:
    - ademcatamak@gmail.com